# Generated by Django 5.0.7 on 2025-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='hi', upload_to='images/events'),
            preserve_default=False,
        ),
    ]
