# Generated by Django 5.0.7 on 2025-03-17 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_event_name_event_title_event_image'),
        ('student', '0002_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_students',
            field=models.ManyToManyField(related_name='registered_events', through='student.Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
