# Generated by Django 5.0.7 on 2025-03-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_event_registered_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
