# Generated by Django 5.0.7 on 2025-03-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='g_number',
            field=models.CharField(default='G00450013', max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
