# Generated by Django 5.0.7 on 2025-03-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_profile_g_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='g_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
